name: Gerar Animação da Cobrinha

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Esse é o passo novo que resolve o erro da foto!
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar a cobrinha
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Salvar a animação no repositório
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: output
          token: ${{ secrets.GITHUB_TOKEN }}
